"""codes table

Revision ID: 02315f501ce5
Revises: 1591eca1db75
Create Date: 2018-05-20 10:57:21.167779

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02315f501ce5'
down_revision = '1591eca1db75'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('code',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('code')
    # ### end Alembic commands ###
