"""empty message

Revision ID: 0f2252093794
Revises: a1ecb07dc9c0
Create Date: 2019-08-27 17:05:59.942082

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f2252093794'
down_revision = 'a1ecb07dc9c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assignment', sa.Column('time_limit', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assignment', 'time_limit')
    # ### end Alembic commands ###
