"""assignments table

Revision ID: 1591eca1db75
Revises: bc3559ceafb9
Create Date: 2018-05-20 10:55:32.113670

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1591eca1db75'
down_revision = 'bc3559ceafb9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assignment', sa.Column('course_id', sa.Integer(), nullable=True))
    op.add_column('assignment', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('assignment', sa.Column('title', sa.String(length=100), nullable=True))
    op.create_unique_constraint(None, 'assignment', ['title'])
    op.create_foreign_key(None, 'assignment', 'course', ['course_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'assignment', type_='foreignkey')
    op.drop_constraint(None, 'assignment', type_='unique')
    op.drop_column('assignment', 'title')
    op.drop_column('assignment', 'description')
    op.drop_column('assignment', 'course_id')
    # ### end Alembic commands ###
