"""empty message

Revision ID: 2c5d9595ca46
Revises: 42bb3f935c16
Create Date: 2019-09-01 17:14:21.766244

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2c5d9595ca46'
down_revision = '42bb3f935c16'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('solution', 'execution_time')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('solution', sa.Column('execution_time', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
