"""users table

Revision ID: 4d257f97640f
Revises: cc5c65fb6d0f
Create Date: 2019-06-16 23:27:03.226688

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d257f97640f'
down_revision = 'cc5c65fb6d0f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('solution', sa.Column('result', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('solution', 'result')
    # ### end Alembic commands ###
