"""solutions table

Revision ID: 577c459b229c
Revises: 5efdc42626e7
Create Date: 2018-05-21 00:42:28.018065

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '577c459b229c'
down_revision = '5efdc42626e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assignment', sa.Column('solution_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'assignment', 'solution', ['solution_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'assignment', type_='foreignkey')
    op.drop_column('assignment', 'solution_id')
    # ### end Alembic commands ###
