"""solutions table

Revision ID: 5b85e27fe7f1
Revises: 3abce4b17caf
Create Date: 2019-05-15 00:11:35.058108

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b85e27fe7f1'
down_revision = '3abce4b17caf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('solution', sa.Column('is_submitted', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('solution', 'is_submitted')
    # ### end Alembic commands ###
