"""courses table

Revision ID: 5efdc42626e7
Revises: 2f4991ce5550
Create Date: 2018-05-20 23:55:22.306487

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5efdc42626e7'
down_revision = '2f4991ce5550'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['code_id'], ['code.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('solution',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('code_id', sa.Integer(), nullable=True),
    sa.Column('is_completed', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['code_id'], ['code.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.add_column('assignment', sa.Column('test_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'assignment', 'test', ['test_id'], ['id'])
    op.add_column('course', sa.Column('creator_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'course', 'user', ['creator_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'course', type_='foreignkey')
    op.drop_column('course', 'creator_id')
    op.drop_constraint(None, 'assignment', type_='foreignkey')
    op.drop_column('assignment', 'test_id')
    op.drop_table('solution')
    op.drop_table('test')
    # ### end Alembic commands ###
