"""empty message

Revision ID: 9842cb08a405
Revises: 0f2252093794
Create Date: 2019-08-28 14:44:20.428764

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9842cb08a405'
down_revision = '0f2252093794'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assignment', sa.Column('test_data', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assignment', 'test_data')
    # ### end Alembic commands ###
