"""users table

Revision ID: 9f67c3d69cc4
Revises: 02315f501ce5
Create Date: 2018-05-20 11:44:05.748506

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f67c3d69cc4'
down_revision = '02315f501ce5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('auto_save_code', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'auto_save_code')
    # ### end Alembic commands ###
