"""empty message

Revision ID: a1ecb07dc9c0
Revises: 4d257f97640f
Create Date: 2019-08-27 16:45:01.057377

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1ecb07dc9c0'
down_revision = '4d257f97640f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assignment', sa.Column('sample_input', sa.Text(), nullable=True))
    op.add_column('assignment', sa.Column('sample_output', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assignment', 'sample_output')
    op.drop_column('assignment', 'sample_input')
    # ### end Alembic commands ###
