"""empty message

Revision ID: b6ad7cea65b0
Revises: 9842cb08a405
Create Date: 2019-08-30 17:03:33.741525

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6ad7cea65b0'
down_revision = '9842cb08a405'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('solution', sa.Column('execution_time', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('solution', 'execution_time')
    # ### end Alembic commands ###
