"""templates table

Revision ID: cc5c65fb6d0f
Revises: 5b85e27fe7f1
Create Date: 2019-06-09 15:05:41.262997

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc5c65fb6d0f'
down_revision = '5b85e27fe7f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('template',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['code_id'], ['code.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.add_column('assignment', sa.Column('template_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'assignment', 'template', ['template_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'assignment', type_='foreignkey')
    op.drop_column('assignment', 'template_id')
    op.drop_table('template')
    # ### end Alembic commands ###
