"""codes table

Revision ID: eee5ba0a8f64
Revises: f8ccee4de99f
Create Date: 2018-06-03 14:35:21.711595

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eee5ba0a8f64'
down_revision = 'f8ccee4de99f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('code', sa.Column('path', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('code', 'path')
    # ### end Alembic commands ###
